backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pagine"
    label: "Pagine"
    files:
      - file: "data/settings.json"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Titolo Hero", name: "hero_title", widget: "string"}
          - {label: "Sottotitolo Hero", name: "hero_sub", widget: "text"}
